# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
undo_backspace: true
matches:
  - trigger: ":hl"
    replace: |
      {{< highlight json >}}
      {{< /highlight >}}
  - trigger: ":note"
    replace: |
      {{< note title="" type="warning|question|info|error|tip|note" >}}
      {{< /note >}}
  - trigger: ":schema"
    replace: |
      {{< schema data="file.json" >}}
  - trigger: ":badge"
    replace: |
      {{< badge color="denim" >}}Enterprise{{< /badge >}}
  - trigger: ":button"
    replace: |
      {{< button-group >}}
      {{< button url="URL" text="TEXT" >}}<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
      </svg>
      {{< /button >}}
      {{< button url="URL" type="inversed" >}}go.sum validator{{< /button >}}
      {{< /button-group >}}
  - trigger: ":term"
    replace: |
      {{< terminal title="Term" >}}
      {{< /terminal >}}
  - trigger: ":kra"
    replace: |
      {
      "version": 3,
      "$schema": "https://www.krakend.io/schema/krakend.json",
      "host": ["http://localhost:8080"],
      "debug_endpoint": true,
      "echo_endpoint": true,
      "endpoints": [{
        "endpoint": "/test",
        "backend": [{
          "url_pattern": "/__debug/test"
      }]
      }]
  - trigger: ":chick"
    replace: ":sunny: :chicken:"
  - trigger: ":br"
    replace: "Best regards,"
  - trigger: ":web"
    replace: "~/git/devopsfaith/website"
  - trigger: ":meet"
    replace: "https://krakend.pipedrive.com/scheduler/92vwQ3Ho/krakend-meeting"
  - trigger: ":agameet"
    replace: https://krakend.pipedrive.com/scheduler/6mB4q3FG/krakend-meeting
  - trigger: ":docs"
    replace: "~/git/devopsfaith/website/content/docs"
  # Edit the espanso configuration
  - trigger: ":g2"
    replace: "https://www.g2.com/products/krakend-api-gateway/reviews"
  - trigger: ":espanso"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "code ~/.config/espanso/default.yml"

  - trigger: ":dot"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "code ~/.dotfiles"
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
